#!/bin/bash

#SBATCH --job-name=autoreject
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20G
#SBATCH --time=02:00:00

set -e
set -x

singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
